---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp 
  yum: name={{ item }} state=present
  with_items:
    - ntp
    - libselinux-python

- name: Kernel optimize
  script: kernel_optimize.sh
  ignore_errors: True

- name: Configure ntp file
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
