---

- hosts: salt-master
  remote_user: root

  tasks:
    - name: Install epel repostitory
      yum: pkg=epel-release state=latest

    - name: ensure salt-master is at the latest version
      yum: pkg=salt-master state=latest  

    - name: write the salt-minion config file
      template: src=templates/master.j2 dest=/etc/salt/master

    - file: path={{ base_root }} state=directory mode=0755
    - file: path={{ pillar_root }} state=directory mode=0755

    - name: ensure that salt-master is started
      service: name=salt-master state=started

- hosts: salt-minion
  remote_user: root

  tasks:
    - name: Install epel repostitory
      yum: pkg=epel-release state=latest

    - name: ensure salt-minion is at the latest version
      yum: pkg=salt-minion state=latest

    - name: write the salt-minion config file
      template: src=templates/minion.j2 dest=/etc/salt/minion

    - name: ensure that salt-minion is started
      service: name=salt-minion state=started
