---

- name: Install memcached package
  yum: pkg=memcached state=present

- name: write the memcached config file
  template: src=../templates/memcached.j2 dest=/etc/sysconfig/memcached mode=0644
  notify:
  -  restart memcached

- name: ensure memcached is running
  service: name=memcached state=started enabled=yes
