---

 - hosts: dev
   vars:
     owner: www-data
     pid: /var/run/nginx.pid
     worker_connections: 1024
     php_sock: /var/run/php/php7.0-fpm.sock
     domain: demo.vqiu.cn
   
   roles:
     - php-7
     - mariadb
     - nginx
     - site_deploy
