---
- name: Install ipvsadm packages 
  yum: name={{ item }} state=present
  with_items: 
    - gcc
    - make
    - openssl-devel
    - popt-devel
    - libnl-devel
    - kernel-devel
    - ipvsadm
- name: Stop iptables stop
  service: name=iptables state=stopped enabled=no
